application: gp-test-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /tickets/.*
  script: home.app

- url: /notes/create
  script: home.app

- url: /notes/get
  script: home.app
